export const CHANGE_USER_VALUES = 'CHANGE_USER_VALUES'
export const ADD_ITEM = 'ADD_ITEM'
export const EDIT_ITEM = 'EDIT_ITEM'
export const REMOVE_ITEM = 'REMOVE_ITEM'
export const SAVE_ITEM = 'SAVE_ITEM'
export const CANCEL_EDIT_ITEM = 'CANCEL_EDIT_ITEM'
export const SEARCH_ITEM = 'SEARCH_ITEM'
